media: content/blog

content:
  - name: blog
    label: Blog Posts
    type: collection
    path: content/blog
    format: yaml-frontmatter
    filename:
      template: "{primary}.md"
      field: true 
    fields:
      - name: title
        label: 标题
        type: string
        required: true
      
      - name: description
        label: Description
        type: text
      
      - name: date
        label: 日期
        type: date
        default: "Last Modified"
        # hidden: true
      
      - name: tags
        label: 标签
        type: string
        list: true   # 关键：开启数组模式
      
      - name: body
        label: 内容
        type: rich-text
        required: true
  - name: introduce
    label: 自我介绍
    type: file
    path: content/about.md
    fields:
      - name: body
        label: 内容
        type: rich-text